<?php

namespace app\modules\api\controllers;


use yii\helpers\ArrayHelper;
use yii\web\Response;
use yii\web\UnauthorizedHttpException;

class RestController extends \yii\rest\Controller
{
    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            [
                'class' => \yii\filters\ContentNegotiator::className(),
                'formats' => [
                    'application/json' => \yii\web\Response::FORMAT_JSON,
                ],
            ],
        ]);
    }

    public function init()
    {
        parent::init();
        \Yii::$app->response->format = Response::FORMAT_JSON;
    }

    public function beforeAction($action)
    {
        $token = $this->request->getHeaders()->get('Authorization');

        if (!$this->isValidToken($token)) {
            throw new UnauthorizedHttpException();
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    private function isValidToken($token)
    {
        if ($token == 'Bearer ' . $this->module->params['token']) {
            return true;
        }

        return false;
    }
}